version: '3.8'

services:
  
  # Serviço para a aplicação Laravel  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "php artisan migrate && php artisan serve --host 0.0.0.0"
    volumes:
      - .:/var/www/html
    networks:
      - my-network
    depends_on:
      - my-postgres

  # Serviço para o banco de dados PostgreSQL
  my-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: estrategia_wms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

# Redes, conexão entre as aplicações
networks:
  my-network:
    driver: bridge

# Volumes, salvar o back-up do PostgreSQL
volumes:
  postgres_data: